name: Docker
on:
  push:
    branches: [master]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create SHA variable
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log In to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mikeyaworski
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-single-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-single-buildx
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mikeyaworski/utility-discord-bot:${{ steps.vars.outputs.sha }},mikeyaworski/utility-discord-bot:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
