name: Docker
on:
  push:
    branches: [master]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log In to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mikeyaworski
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push SHA
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mikeyaworski/utility-discord-bot:$(git rev-parse --short HEAD)
    - name: Build and push latest
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mikeyaworski/utility-discord-bot:latest
